server:
  port: 9001

spring:
  application:
    name: kuke-board-comment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.225.129:3306/comment
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: false
#    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: 192.168.225.129
      port: 6379
  kafka:
    bootstrap-servers: 192.168.225.129:9092
